
- name: check brew presence
  stat:
    path: /usr/local/bin/brew
  register: brew

- block:
    - name: download homebrew
      get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/master/install
        dest: /tmp/install-brew.rb

    - name: install homebrew
      command: /usr/bin/ruby -e /tmp/install-brew.rb
  when: not brew.stat.exists

- name: install common packages
  homebrew:
    name: "{{packages}}"

- name: install custom packages
  homebrew:
    name:
      - vcprompt
      - bash-completion
      - git
      - pyenv
      - the_silver_searcher

- name: copy macos only scripts
  copy:
    src: "{{item}}"
    dest: "~/bin/{{item}}"
  with_items:
    - imgcat
    - netstat

- name:
  homebrew_cask:
    name:
      - iterm2
      - visual-studio-code

- name: create custom iterm2 config dir
  file:
    path: ~/.config/iterm2
    state: directory

- name: copy iterm2 config
  copy:
    src: com.googlecode.iterm2.plist
    dest: ~/.config/iterm2/com.googlecode.iterm2.plist

- name: create user KeyBindings dir
  file:
    path: ~/Library/KeyBindings
    state: directory

- name: copy custom keymap for classic home-end behaviour
  copy:
    src: DefaultKeyBinding.dict
    dest: ~/Library/KeyBindings/DefaultKeyBinding.dict
