
- name: install common packages
  apt:
    name: "{{item}}"
  with_items: "{{packages}}"

- name: install custom packages
  apt:
    name: "{{item}}"
  with_items:
    - silversearcher-ag

- name: check vcprompt presence
  stat:
    path: ~/bin/vcprompt
  register: vcprompt

- name: build vcprompt
  include_tasks: vcprompt.yaml
  when: not vcprompt.stat.exists


# - name: install pyenv
# TODO
