
- name: install some python deps
  sudo: ansible_os_family != 'Darwin'
  pip:
    name: [requests, progressbar]

- name: get current python
  command: which python
  register: which_python
  changed_when: false

- set_fact:
    python_executable: "{{ which_python.stdout }}"

- name: install cli tools
  template:
    src: "{{ item }}"
    dest: "~/bin/{{ item }}"
    mode: +x
  with_items:
    - lamp
    - sleep-timer
